
/**
 * whatsapp_bridge.js  (auto-generated by WHbot.py — do not edit directly)
 *
 * WhatsApp automation bridge built on whatsapp-web.js.
 * Exposes a small JSON HTTP API consumed by WHbot.py.
 *
 * Endpoints:
 *   GET  /health
 *   GET  /status
 *   POST /login
 *   GET  /qr
 *   POST /logout
 *   POST /join-group        body { link }
 *   GET  /admin/:groupId
 *   GET  /members/:groupId
 *   POST /add               body { groupId, contacts[], batchSize?, delaySeconds? }
 *   GET  /jobs/:jobId
 *   POST /jobs/:jobId/cancel
 */

const http = require('http');
const path = require('path');
const { Client, LocalAuth } = require('whatsapp-web.js');

const PORT             = parseInt(process.env.BRIDGE_PORT         || '3000', 10);
const BRIDGE_TOKEN     = process.env.BRIDGE_TOKEN || '';
const DEFAULT_BATCH_SIZE     = parseInt(process.env.BATCH_SIZE          || '4',  10);
const DEFAULT_BATCH_DELAY_MS = parseInt(process.env.BATCH_DELAY_SECONDS || '30', 10) * 1000;
const AUTH_PATH = process.env.WWEBJS_AUTH_PATH || path.join(__dirname, '.wwebjs_auth');

let client        = null;
let clientStarted = false;
let qr            = null;
let readyInfo     = null;
let initError     = null;
let intentionalLogout = false;

const jobs   = new Map();
let   jobSeq = 1;

const sleep = (ms) => new Promise((resolve) => setTimeout(resolve, ms));

/* ─── browser detection ─────────────────────────────────────────────────── */

function findBrowserPath() {
  if (process.env.PUPPETEER_EXECUTABLE_PATH) return process.env.PUPPETEER_EXECUTABLE_PATH;
  const fs = require('fs');
  const candidates = [
    'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe',
    'C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe',
    process.env.LOCALAPPDATA ? `${process.env.LOCALAPPDATA}\\Google\\Chrome\\Application\\chrome.exe` : null,
    'C:\\Program Files\\Microsoft\\Edge\\Application\\msedge.exe',
    'C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe',
    '/usr/bin/google-chrome',
    '/usr/bin/chromium',
    '/usr/bin/chromium-browser',
    '/usr/bin/microsoft-edge',
    '/opt/google/chrome/chrome',
    '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',
  ];
  for (const c of candidates) { if (c && fs.existsSync(c)) return c; }
  return null;
}

/* ─── WhatsApp client ───────────────────────────────────────────────────── */

function createClient() {
  const executablePath = findBrowserPath();
  if (executablePath) {
    console.log(`[whatsapp] using browser: ${executablePath}`);
  } else {
    console.warn('[whatsapp] no Chrome/Edge found — puppeteer will use its bundled default.');
  }

  client = new Client({
    authStrategy: new LocalAuth({ dataPath: AUTH_PATH }),
    puppeteer: {
      headless: true,
      executablePath,
      args: [
        '--no-sandbox', '--disable-setuid-sandbox', '--disable-dev-shm-usage',
        '--disable-gpu', '--disable-background-networking', '--disable-default-apps',
        '--disable-extensions', '--disable-sync', '--no-first-run',
      ],
    },
  });

  client.on('qr', (qrString) => {
    qr = qrString; readyInfo = null; initError = null;
    console.log('[whatsapp] new QR generated');
  });
  client.on('authenticated', () => console.log('[whatsapp] authenticated — session saved'));
  client.on('auth_failure',  (msg) => { console.error('[whatsapp] auth failure:', msg); qr = null; });
  client.on('ready', () => {
    qr = null; readyInfo = client.info; initError = null;
    console.log(`[whatsapp] ready as ${client.info.pushname || ''} (${mySerialized()})`);
  });
  client.on('disconnected', (reason) => {
    console.warn('[whatsapp] disconnected:', reason);
    qr = null; readyInfo = null; client = null; clientStarted = false;
    if (!intentionalLogout) {
      console.log('[whatsapp] unexpected disconnect — auto-reconnecting in 5 s…');
      setTimeout(() => {
        if (!clientStarted && !intentionalLogout) {
          console.log('[whatsapp] auto-reconnecting…');
          createClient(); clientStarted = true;
          client.initialize().catch((err) => {
            initError = err && err.message ? err.message : String(err);
            console.error('[whatsapp] auto-reconnect failed:', err);
          });
        }
      }, 5000);
    } else {
      intentionalLogout = false;
    }
  });
}

function mySerialized() {
  if (!client || !client.info) return null;
  if (client.info.wid && client.info.wid._serialized) return client.info.wid._serialized;
  if (client.info.me) return client.info.me + '@c.us';
  return null;
}

function ensureLoggedIn() {
  if (!client || !readyInfo) {
    const err = new Error('WhatsApp is not logged in. Use POST /login first.');
    err.status = 401; throw err;
  }
}

function extractInviteCode(link) {
  if (!link) return null;
  const s = String(link).trim();
  const m = s.match(/(?:chat\.whatsapp\.com\/|whatsapp\.com\/)([A-Za-z0-9_-]{10,})/);
  if (m) return m[1];
  const bare = s.match(/^([A-Za-z0-9_-]{16,32})$/);
  return bare ? bare[1] : null;
}

/* ─── group operations ──────────────────────────────────────────────────── */

async function joinGroup(link) {
  ensureLoggedIn();
  const code = extractInviteCode(link);
  if (!code) throw new Error('Invalid WhatsApp group invite link.');
  const groupId = await client.acceptInvite(code);
  let name = '';
  try { const chat = await client.getChatById(groupId); name = chat.name || ''; } catch {}
  return { groupId, name };
}

async function getChat(groupId) {
  ensureLoggedIn();
  return client.getChatById(groupId);
}

function normalizeId(serialized) {
  if (!serialized) return null;
  const s = String(serialized).trim();
  const m = s.match(/^(\d+)@(c\.us|lid)$/);
  return m ? { server: m[2], user: m[1] } : null;
}

function sameAccount(a, b) {
  const na = normalizeId(a), nb = normalizeId(b);
  if (!na || !nb) return String(a) === String(b);
  return na.server === nb.server && na.user === nb.user;
}

function participantMatches(p, me) {
  return sameAccount(p && p.id && (p.id._serialized || p.id), me);
}

async function checkAdminInBrowser(groupId) {
  return client.pupPage.evaluate(async (groupId) => {
    const wid = (id) => {
      if (!id) return null;
      if (typeof id === 'string') return id;
      return id._serialized || id.$1 || null;
    };
    const chatWid = window.require('WAWebWidFactory').createWid(groupId);
    let chat =
      window.require('WAWebCollections').Chat.get(chatWid) ||
      (await window.require('WAWebFindChatAction').findOrCreateLatestChat(chatWid))?.chat;
    if (!chat || !chat.groupMetadata) return { isAdmin: false, reason: 'not_group' };
    try {
      await window.require('WAWebGroupQueryJob').queryAndUpdateGroupMetadataById({ id: groupId });
    } catch {}
    if (typeof chat.iAmAdmin === 'function') return { isAdmin: chat.iAmAdmin() };
    const { getMaybeMeLidUser, getMaybeMePnUser } = window.require('WAWebLidMigrationUtils');
    const me =
      wid(getMaybeMePnUser()) ||
      wid(getMaybeMeLidUser()) ||
      wid(window.require('WAWebUserPrefsMeUser').getMaybeMeUser());
    if (!me) return { isAdmin: false, reason: 'no_me' };
    const meUser = me.split('@')[0];
    const participants = chat.groupMetadata.participants;
    const list = participants._models || participants;
    for (const p of list) {
      const pid = wid(p.id);
      if (!pid) continue;
      const same = pid === me || pid.split('@')[0] === meUser || me.split('@')[0] === pid.split('@')[0];
      if (same) return { isAdmin: !!(p.isAdmin || p.isSuperAdmin) };
    }
    return { isAdmin: false };
  }, groupId);
}

async function isAdmin(groupId) {
  ensureLoggedIn();
  const me = mySerialized();
  if (!me) return false;
  try {
    const result = await checkAdminInBrowser(groupId);
    if (result && result.reason !== 'not_group' && result.reason !== 'no_me') return !!result.isAdmin;
  } catch (browserErr) {
    console.warn('[whatsapp] browser admin check failed, trying library:', browserErr && browserErr.message || browserErr);
  }
  try {
    const chat = await getChat(groupId);
    const participant = (chat.participants || []).find((p) => participantMatches(p, me));
    return !!(participant && participant.isAdmin);
  } catch (err) {
    console.warn(`[whatsapp] Could not read membership for ${groupId}: ${err && err.message ? err.message : err}`);
    return false;
  }
}

async function getMembers(groupId) {
  const chat = await getChat(groupId);
  const participants = chat.participants || [];
  return { count: participants.length, participants: participants.map((p) => p.id._serialized) };
}

/* ─── batch-add jobs ────────────────────────────────────────────────────── */

function startAddJob(groupId, contacts, opts = {}) {
  ensureLoggedIn();
  const batchSize = opts.batchSize || DEFAULT_BATCH_SIZE;
  const delayMs   = opts.delayMs !== undefined ? opts.delayMs : DEFAULT_BATCH_DELAY_MS;
  const job = {
    id: `job_${jobSeq++}`, status: 'running',
    groupId, contacts, batchSize, delayMs,
    doneBatches: 0, totalBatches: 0,
    added: 0, failed: 0, error: null, result: null,
    cancelled: false, startedAt: Date.now(),
  };
  jobs.set(job.id, job);
  runAddJob(job).catch((err) => { job.status = 'error'; job.error = err.message || String(err); });
  return { jobId: job.id };
}

async function runAddJob(job) {
  const chat     = await getChat(job.groupId);
  const existing = new Set((chat.participants || []).map((p) => p.id._serialized));
  const toAdd    = job.contacts.filter((c) => !existing.has(c));
  const alreadyCount = job.contacts.length - toAdd.length;

  const batches = [];
  for (let i = 0; i < toAdd.length; i += job.batchSize) batches.push(toAdd.slice(i, i + job.batchSize));
  job.totalBatches = batches.length;

  const added = [], failed = [];

  function normalizeAddResult(raw, fallbackBatch) {
    if (!raw) return fallbackBatch.map((id) => ({ id, code: 500, error: 'no response' }));
    if (Array.isArray(raw)) return raw;
    if (typeof raw === 'object') {
      return Object.entries(raw).map(([key, val]) => ({
        id: (val && val.jid) || key,
        code: (val && (val.code ?? val.status)) ?? 500,
        error: (val && val.message) || undefined,
      }));
    }
    return fallbackBatch.map((id) => ({ id, code: 500, error: 'unexpected response' }));
  }

  for (let i = 0; i < batches.length; i++) {
    if (job.cancelled) { job.status = 'cancelled'; return; }
    const batch = batches[i];
    let results = [];
    try {
      results = normalizeAddResult(await chat.addParticipants(batch), batch);
    } catch (err) {
      for (const c of batch) {
        try { results.push(...normalizeAddResult(await chat.addParticipants([c]), [c])); }
        catch (e2) { results.push({ id: c, code: 500, error: e2.message }); }
      }
    }
    for (const r of results) {
      const id = r.id || r._serialized;
      if (r.code === 200) added.push(id);
      else failed.push({ id, code: r.code, error: r.error });
    }
    job.doneBatches = i + 1;
    job.added  = added.length;
    job.failed = failed.length;
    if (i < batches.length - 1) await sleep(job.delayMs);
  }
  job.status = 'done';
  job.result = { added, failed, alreadyCount, totalBatches: batches.length };
}

/* ─── HTTP API ──────────────────────────────────────────────────────────── */

function send(res, status, body) {
  res.writeHead(status, { 'Content-Type': 'application/json' });
  res.end(JSON.stringify(body));
}
function sendError(res, err) {
  console.error('[bridge] error:', err);
  send(res, err.status || 500, { error: err.message || String(err) });
}

const MAX_BODY_BYTES = 5 * 1024 * 1024;
function readBody(req) {
  return new Promise((resolve, reject) => {
    let data = '';
    req.on('data', (chunk) => {
      data += chunk;
      if (data.length > MAX_BODY_BYTES) {
        const err = new Error('Request body too large'); err.status = 413;
        reject(err); req.destroy();
      }
    });
    req.on('end', () => {
      if (!data) return resolve({});
      try { resolve(JSON.parse(data)); }
      catch { const err = new Error('Invalid JSON body'); err.status = 400; reject(err); }
    });
    req.on('error', reject);
  });
}
function authOk(req) {
  if (!BRIDGE_TOKEN) return true;
  return (req.headers['authorization'] || '') === `Bearer ${BRIDGE_TOKEN}`;
}

const server = http.createServer(async (req, res) => {
  try {
    if (!authOk(req)) return send(res, 401, { error: 'Unauthorized' });
    const url    = req.url.split('?')[0];
    const method = req.method;

    if (method === 'GET'  && url === '/health') return send(res, 200, { ok: true });

    if (method === 'GET'  && url === '/status')
      return send(res, 200, {
        loggedIn: !!readyInfo,
        info: readyInfo ? { pushname: readyInfo.pushname, me: mySerialized() } : null,
        error: initError,
      });

    if (method === 'POST' && url === '/login') {
      if (clientStarted && !readyInfo) {
        try { await client.destroy(); } catch (err) { console.warn('[whatsapp] cleanup failed:', err.message || err); }
        client = null; clientStarted = false; qr = null; initError = null;
        createClient();
      }
      if (!client) createClient();
      if (!clientStarted) {
        clientStarted = true;
        client.initialize().catch((err) => {
          initError = err && err.message ? err.message : String(err);
          console.error('[whatsapp] initialize failed:', err);
        });
      }
      return send(res, 200, {
        status: readyInfo ? 'ready' : initError ? 'error' : 'pending',
        info:   readyInfo ? mySerialized() : null,
        error:  initError,
      });
    }

    if (method === 'GET' && url === '/qr') {
      if (readyInfo)  return send(res, 200, { state: 'ready' });
      if (initError)  return send(res, 200, { state: 'error', error: initError });
      if (qr)         return send(res, 200, { state: 'waiting', qr });
      return send(res, 200, { state: 'pending' });
    }

    if (method === 'POST' && url === '/logout') {
      ensureLoggedIn();
      intentionalLogout = true;
      await client.logout();
      readyInfo = null; qr = null;
      return send(res, 200, { ok: true });
    }

    if (method === 'POST' && url === '/join-group') {
      const body = await readBody(req);
      return send(res, 200, await joinGroup(body.link));
    }

    const adminMatch = url.match(/^\/admin\/(.+)$/);
    if (method === 'GET' && adminMatch)
      return send(res, 200, { isAdmin: await isAdmin(decodeURIComponent(adminMatch[1])) });

    const membersMatch = url.match(/^\/members\/(.+)$/);
    if (method === 'GET' && membersMatch)
      return send(res, 200, await getMembers(decodeURIComponent(membersMatch[1])));

    if (method === 'POST' && url === '/add') {
      const body = await readBody(req);
      if (!body.groupId || !Array.isArray(body.contacts) || !body.contacts.length)
        return send(res, 400, { error: 'groupId and a non-empty contacts array are required' });
      return send(res, 200, startAddJob(body.groupId, body.contacts, {
        batchSize: body.batchSize,
        delayMs:   body.delaySeconds ? body.delaySeconds * 1000 : undefined,
      }));
    }

    const cancelMatch = url.match(/^\/jobs\/([^/]+)\/cancel$/);
    if (method === 'POST' && cancelMatch) {
      const job = jobs.get(cancelMatch[1]);
      if (!job) return send(res, 404, { error: 'Job not found' });
      job.cancelled = true;
      return send(res, 200, { ok: true });
    }

    const jobMatch = url.match(/^\/jobs\/([^/]+)$/);
    if (method === 'GET' && jobMatch) {
      const job = jobs.get(jobMatch[1]);
      if (!job) return send(res, 404, { error: 'Job not found' });
      const { result, ...pub } = job;
      return send(res, 200, job.status === 'done' ? { ...pub, result } : pub);
    }

    send(res, 404, { error: 'Not found' });
  } catch (err) {
    sendError(res, err);
  }
});

server.listen(PORT, '127.0.0.1', () => {
  console.log(`[bridge] listening on http://127.0.0.1:${PORT}`);
  const fs          = require('fs');
  const sessionPath = require('path').join(AUTH_PATH, 'session');
  if (fs.existsSync(sessionPath)) {
    console.log('[whatsapp] saved session found — restoring automatically…');
    createClient(); clientStarted = true;
    client.initialize().catch((err) => {
      initError = err && err.message ? err.message : String(err);
      console.error('[whatsapp] auto-restore failed:', err);
    });
  } else {
    console.log('[whatsapp] no saved session — waiting for /login');
  }
});
