#!/usr/bin/env python3
"""
WHbot.py — Single-file WhatsApp Group Manager Telegram Bot.

Embeds the Node.js WhatsApp bridge script as a string, writes it to disk on
startup, and spawns it as a subprocess automatically.
Also embeds the VCF parser inline — no separate files needed.

Workflow (per user):
  1. /login                     -> QR code to link your WhatsApp account
  2. /join <group_link>         -> the logged-in number joins the group
  3. wait for admin rights      -> bot polls until the number is an admin
  4. send a .vcf file           -> contacts are parsed and batch-added
  5. final report               -> added count + final group member count

Env vars:
  BOT_TOKEN                 (required) Telegram bot token
  ALLOWED_USER_ID           optional: restrict to one Telegram user id
  BRIDGE_HOST / BRIDGE_PORT default 127.0.0.1 / 3000
  BRIDGE_TOKEN              optional shared secret for the bridge
  BATCH_SIZE                default 4 contacts per batch
  BATCH_DELAY_SECONDS       default 30s delay between batches
  ADMIN_POLL_SECONDS        default 20s admin-rights poll interval
  ADMIN_WAIT_TIMEOUT_SECONDS default 1800s (30 min) admin wait before abort
  ADD_POLL_SECONDS          default 12s job-progress poll interval
  DEFAULT_COUNTRY_CODE      default 91 (India); prepended to numbers without one
  DATA_DIR                  dir for persistent state (.wwebjs_auth + session_owner.json)
                            Point at a persistent volume on Railway/Render (/data)
  PORT                      health-check HTTP port (default 8080)
"""

from __future__ import annotations

import asyncio
import io
import json
import logging
import os
import re
import signal
import subprocess
import sys
import tempfile
import time
from urllib import error as urllib_error, request as urllib_request
from urllib.parse import quote

import qrcode
from telegram import InlineKeyboardButton, InlineKeyboardMarkup, InputFile, Update
from telegram.ext import (
    Application,
    CallbackQueryHandler,
    CommandHandler,
    ContextTypes,
    MessageHandler,
    filters,
)

# ---------------------------------------------------------------------------
# Embedded Node.js WhatsApp bridge — written to DATA_DIR on first run
# ---------------------------------------------------------------------------

BRIDGE_JS = r"""
/**
 * whatsapp_bridge.js  (auto-generated by WHbot.py — do not edit directly)
 *
 * WhatsApp automation bridge built on whatsapp-web.js.
 * Exposes a small JSON HTTP API consumed by WHbot.py.
 *
 * Endpoints:
 *   GET  /health
 *   GET  /status
 *   POST /login
 *   GET  /qr
 *   POST /logout
 *   POST /join-group        body { link }
 *   GET  /admin/:groupId
 *   GET  /members/:groupId
 *   POST /add               body { groupId, contacts[], batchSize?, delaySeconds? }
 *   GET  /jobs/:jobId
 *   POST /jobs/:jobId/cancel
 */

const http = require('http');
const path = require('path');
const { Client, LocalAuth } = require('whatsapp-web.js');

const PORT             = parseInt(process.env.BRIDGE_PORT         || '3000', 10);
const BRIDGE_TOKEN     = process.env.BRIDGE_TOKEN || '';
const DEFAULT_BATCH_SIZE     = parseInt(process.env.BATCH_SIZE          || '4',  10);
const DEFAULT_BATCH_DELAY_MS = parseInt(process.env.BATCH_DELAY_SECONDS || '30', 10) * 1000;
const AUTH_PATH = process.env.WWEBJS_AUTH_PATH || path.join(__dirname, '.wwebjs_auth');

let client        = null;
let clientStarted = false;
let qr            = null;
let readyInfo     = null;
let initError     = null;
let intentionalLogout = false;

const jobs   = new Map();
let   jobSeq = 1;

const sleep = (ms) => new Promise((resolve) => setTimeout(resolve, ms));

/* ─── browser detection ─────────────────────────────────────────────────── */

function findBrowserPath() {
  if (process.env.PUPPETEER_EXECUTABLE_PATH) return process.env.PUPPETEER_EXECUTABLE_PATH;
  const fs = require('fs');
  const candidates = [
    'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe',
    'C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe',
    process.env.LOCALAPPDATA ? `${process.env.LOCALAPPDATA}\\Google\\Chrome\\Application\\chrome.exe` : null,
    'C:\\Program Files\\Microsoft\\Edge\\Application\\msedge.exe',
    'C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe',
    '/usr/bin/google-chrome',
    '/usr/bin/chromium',
    '/usr/bin/chromium-browser',
    '/usr/bin/microsoft-edge',
    '/opt/google/chrome/chrome',
    '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',
  ];
  for (const c of candidates) { if (c && fs.existsSync(c)) return c; }
  return null;
}

/* ─── WhatsApp client ───────────────────────────────────────────────────── */

function createClient() {
  const executablePath = findBrowserPath();
  if (executablePath) {
    console.log(`[whatsapp] using browser: ${executablePath}`);
  } else {
    console.warn('[whatsapp] no Chrome/Edge found — puppeteer will use its bundled default.');
  }

  client = new Client({
    authStrategy: new LocalAuth({ dataPath: AUTH_PATH }),
    puppeteer: {
      headless: true,
      executablePath,
      args: [
        '--no-sandbox', '--disable-setuid-sandbox', '--disable-dev-shm-usage',
        '--disable-gpu', '--disable-background-networking', '--disable-default-apps',
        '--disable-extensions', '--disable-sync', '--no-first-run',
      ],
    },
  });

  client.on('qr', (qrString) => {
    qr = qrString; readyInfo = null; initError = null;
    console.log('[whatsapp] new QR generated');
  });
  client.on('authenticated', () => console.log('[whatsapp] authenticated — session saved'));
  client.on('auth_failure',  (msg) => { console.error('[whatsapp] auth failure:', msg); qr = null; });
  client.on('ready', () => {
    qr = null; readyInfo = client.info; initError = null;
    console.log(`[whatsapp] ready as ${client.info.pushname || ''} (${mySerialized()})`);
  });
  client.on('disconnected', (reason) => {
    console.warn('[whatsapp] disconnected:', reason);
    qr = null; readyInfo = null; client = null; clientStarted = false;
    if (!intentionalLogout) {
      console.log('[whatsapp] unexpected disconnect — auto-reconnecting in 5 s…');
      setTimeout(() => {
        if (!clientStarted && !intentionalLogout) {
          console.log('[whatsapp] auto-reconnecting…');
          createClient(); clientStarted = true;
          client.initialize().catch((err) => {
            initError = err && err.message ? err.message : String(err);
            console.error('[whatsapp] auto-reconnect failed:', err);
          });
        }
      }, 5000);
    } else {
      intentionalLogout = false;
    }
  });
}

function mySerialized() {
  if (!client || !client.info) return null;
  if (client.info.wid && client.info.wid._serialized) return client.info.wid._serialized;
  if (client.info.me) return client.info.me + '@c.us';
  return null;
}

function ensureLoggedIn() {
  if (!client || !readyInfo) {
    const err = new Error('WhatsApp is not logged in. Use POST /login first.');
    err.status = 401; throw err;
  }
}

function extractInviteCode(link) {
  if (!link) return null;
  const s = String(link).trim();
  const m = s.match(/(?:chat\.whatsapp\.com\/|whatsapp\.com\/)([A-Za-z0-9_-]{10,})/);
  if (m) return m[1];
  const bare = s.match(/^([A-Za-z0-9_-]{16,32})$/);
  return bare ? bare[1] : null;
}

/* ─── group operations ──────────────────────────────────────────────────── */

async function joinGroup(link) {
  ensureLoggedIn();
  const code = extractInviteCode(link);
  if (!code) throw new Error('Invalid WhatsApp group invite link.');
  const groupId = await client.acceptInvite(code);
  let name = '';
  try { const chat = await client.getChatById(groupId); name = chat.name || ''; } catch {}
  return { groupId, name };
}

async function getChat(groupId) {
  ensureLoggedIn();
  return client.getChatById(groupId);
}

function normalizeId(serialized) {
  if (!serialized) return null;
  const s = String(serialized).trim();
  const m = s.match(/^(\d+)@(c\.us|lid)$/);
  return m ? { server: m[2], user: m[1] } : null;
}

function sameAccount(a, b) {
  const na = normalizeId(a), nb = normalizeId(b);
  if (!na || !nb) return String(a) === String(b);
  return na.server === nb.server && na.user === nb.user;
}

function participantMatches(p, me) {
  return sameAccount(p && p.id && (p.id._serialized || p.id), me);
}

async function checkAdminInBrowser(groupId) {
  return client.pupPage.evaluate(async (groupId) => {
    const wid = (id) => {
      if (!id) return null;
      if (typeof id === 'string') return id;
      return id._serialized || id.$1 || null;
    };
    const chatWid = window.require('WAWebWidFactory').createWid(groupId);
    let chat =
      window.require('WAWebCollections').Chat.get(chatWid) ||
      (await window.require('WAWebFindChatAction').findOrCreateLatestChat(chatWid))?.chat;
    if (!chat || !chat.groupMetadata) return { isAdmin: false, reason: 'not_group' };
    try {
      await window.require('WAWebGroupQueryJob').queryAndUpdateGroupMetadataById({ id: groupId });
    } catch {}
    if (typeof chat.iAmAdmin === 'function') return { isAdmin: chat.iAmAdmin() };
    const { getMaybeMeLidUser, getMaybeMePnUser } = window.require('WAWebLidMigrationUtils');
    const me =
      wid(getMaybeMePnUser()) ||
      wid(getMaybeMeLidUser()) ||
      wid(window.require('WAWebUserPrefsMeUser').getMaybeMeUser());
    if (!me) return { isAdmin: false, reason: 'no_me' };
    const meUser = me.split('@')[0];
    const participants = chat.groupMetadata.participants;
    const list = participants._models || participants;
    for (const p of list) {
      const pid = wid(p.id);
      if (!pid) continue;
      const same = pid === me || pid.split('@')[0] === meUser || me.split('@')[0] === pid.split('@')[0];
      if (same) return { isAdmin: !!(p.isAdmin || p.isSuperAdmin) };
    }
    return { isAdmin: false };
  }, groupId);
}

async function isAdmin(groupId) {
  ensureLoggedIn();
  const me = mySerialized();
  if (!me) return false;
  try {
    const result = await checkAdminInBrowser(groupId);
    if (result && result.reason !== 'not_group' && result.reason !== 'no_me') return !!result.isAdmin;
  } catch (browserErr) {
    console.warn('[whatsapp] browser admin check failed, trying library:', browserErr && browserErr.message || browserErr);
  }
  try {
    const chat = await getChat(groupId);
    const participant = (chat.participants || []).find((p) => participantMatches(p, me));
    return !!(participant && participant.isAdmin);
  } catch (err) {
    console.warn(`[whatsapp] Could not read membership for ${groupId}: ${err && err.message ? err.message : err}`);
    return false;
  }
}

async function getMembers(groupId) {
  const chat = await getChat(groupId);
  const participants = chat.participants || [];
  return { count: participants.length, participants: participants.map((p) => p.id._serialized) };
}

/* ─── batch-add jobs ────────────────────────────────────────────────────── */

function startAddJob(groupId, contacts, opts = {}) {
  ensureLoggedIn();
  const batchSize = opts.batchSize || DEFAULT_BATCH_SIZE;
  const delayMs   = opts.delayMs !== undefined ? opts.delayMs : DEFAULT_BATCH_DELAY_MS;
  const job = {
    id: `job_${jobSeq++}`, status: 'running',
    groupId, contacts, batchSize, delayMs,
    doneBatches: 0, totalBatches: 0,
    added: 0, failed: 0, error: null, result: null,
    cancelled: false, startedAt: Date.now(),
  };
  jobs.set(job.id, job);
  runAddJob(job).catch((err) => { job.status = 'error'; job.error = err.message || String(err); });
  return { jobId: job.id };
}

async function runAddJob(job) {
  const chat     = await getChat(job.groupId);
  const existing = new Set((chat.participants || []).map((p) => p.id._serialized));
  const toAdd    = job.contacts.filter((c) => !existing.has(c));
  const alreadyCount = job.contacts.length - toAdd.length;

  const batches = [];
  for (let i = 0; i < toAdd.length; i += job.batchSize) batches.push(toAdd.slice(i, i + job.batchSize));
  job.totalBatches = batches.length;

  const added = [], failed = [];

  function normalizeAddResult(raw, fallbackBatch) {
    if (!raw) return fallbackBatch.map((id) => ({ id, code: 500, error: 'no response' }));
    if (Array.isArray(raw)) return raw;
    if (typeof raw === 'object') {
      return Object.entries(raw).map(([key, val]) => ({
        id: (val && val.jid) || key,
        code: (val && (val.code ?? val.status)) ?? 500,
        error: (val && val.message) || undefined,
      }));
    }
    return fallbackBatch.map((id) => ({ id, code: 500, error: 'unexpected response' }));
  }

  for (let i = 0; i < batches.length; i++) {
    if (job.cancelled) { job.status = 'cancelled'; return; }
    const batch = batches[i];
    let results = [];
    try {
      results = normalizeAddResult(await chat.addParticipants(batch), batch);
    } catch (err) {
      for (const c of batch) {
        try { results.push(...normalizeAddResult(await chat.addParticipants([c]), [c])); }
        catch (e2) { results.push({ id: c, code: 500, error: e2.message }); }
      }
    }
    for (const r of results) {
      const id = r.id || r._serialized;
      if (r.code === 200) added.push(id);
      else failed.push({ id, code: r.code, error: r.error });
    }
    job.doneBatches = i + 1;
    job.added  = added.length;
    job.failed = failed.length;
    if (i < batches.length - 1) await sleep(job.delayMs);
  }
  job.status = 'done';
  job.result = { added, failed, alreadyCount, totalBatches: batches.length };
}

/* ─── HTTP API ──────────────────────────────────────────────────────────── */

function send(res, status, body) {
  res.writeHead(status, { 'Content-Type': 'application/json' });
  res.end(JSON.stringify(body));
}
function sendError(res, err) {
  console.error('[bridge] error:', err);
  send(res, err.status || 500, { error: err.message || String(err) });
}

const MAX_BODY_BYTES = 5 * 1024 * 1024;
function readBody(req) {
  return new Promise((resolve, reject) => {
    let data = '';
    req.on('data', (chunk) => {
      data += chunk;
      if (data.length > MAX_BODY_BYTES) {
        const err = new Error('Request body too large'); err.status = 413;
        reject(err); req.destroy();
      }
    });
    req.on('end', () => {
      if (!data) return resolve({});
      try { resolve(JSON.parse(data)); }
      catch { const err = new Error('Invalid JSON body'); err.status = 400; reject(err); }
    });
    req.on('error', reject);
  });
}
function authOk(req) {
  if (!BRIDGE_TOKEN) return true;
  return (req.headers['authorization'] || '') === `Bearer ${BRIDGE_TOKEN}`;
}

const server = http.createServer(async (req, res) => {
  try {
    if (!authOk(req)) return send(res, 401, { error: 'Unauthorized' });
    const url    = req.url.split('?')[0];
    const method = req.method;

    if (method === 'GET'  && url === '/health') return send(res, 200, { ok: true });

    if (method === 'GET'  && url === '/status')
      return send(res, 200, {
        loggedIn: !!readyInfo,
        info: readyInfo ? { pushname: readyInfo.pushname, me: mySerialized() } : null,
        error: initError,
      });

    if (method === 'POST' && url === '/login') {
      if (clientStarted && !readyInfo) {
        try { await client.destroy(); } catch (err) { console.warn('[whatsapp] cleanup failed:', err.message || err); }
        client = null; clientStarted = false; qr = null; initError = null;
        createClient();
      }
      if (!client) createClient();
      if (!clientStarted) {
        clientStarted = true;
        client.initialize().catch((err) => {
          initError = err && err.message ? err.message : String(err);
          console.error('[whatsapp] initialize failed:', err);
        });
      }
      return send(res, 200, {
        status: readyInfo ? 'ready' : initError ? 'error' : 'pending',
        info:   readyInfo ? mySerialized() : null,
        error:  initError,
      });
    }

    if (method === 'GET' && url === '/qr') {
      if (readyInfo)  return send(res, 200, { state: 'ready' });
      if (initError)  return send(res, 200, { state: 'error', error: initError });
      if (qr)         return send(res, 200, { state: 'waiting', qr });
      return send(res, 200, { state: 'pending' });
    }

    if (method === 'POST' && url === '/logout') {
      ensureLoggedIn();
      intentionalLogout = true;
      await client.logout();
      readyInfo = null; qr = null;
      return send(res, 200, { ok: true });
    }

    if (method === 'POST' && url === '/join-group') {
      const body = await readBody(req);
      return send(res, 200, await joinGroup(body.link));
    }

    const adminMatch = url.match(/^\/admin\/(.+)$/);
    if (method === 'GET' && adminMatch)
      return send(res, 200, { isAdmin: await isAdmin(decodeURIComponent(adminMatch[1])) });

    const membersMatch = url.match(/^\/members\/(.+)$/);
    if (method === 'GET' && membersMatch)
      return send(res, 200, await getMembers(decodeURIComponent(membersMatch[1])));

    if (method === 'POST' && url === '/add') {
      const body = await readBody(req);
      if (!body.groupId || !Array.isArray(body.contacts) || !body.contacts.length)
        return send(res, 400, { error: 'groupId and a non-empty contacts array are required' });
      return send(res, 200, startAddJob(body.groupId, body.contacts, {
        batchSize: body.batchSize,
        delayMs:   body.delaySeconds ? body.delaySeconds * 1000 : undefined,
      }));
    }

    const cancelMatch = url.match(/^\/jobs\/([^/]+)\/cancel$/);
    if (method === 'POST' && cancelMatch) {
      const job = jobs.get(cancelMatch[1]);
      if (!job) return send(res, 404, { error: 'Job not found' });
      job.cancelled = true;
      return send(res, 200, { ok: true });
    }

    const jobMatch = url.match(/^\/jobs\/([^/]+)$/);
    if (method === 'GET' && jobMatch) {
      const job = jobs.get(jobMatch[1]);
      if (!job) return send(res, 404, { error: 'Job not found' });
      const { result, ...pub } = job;
      return send(res, 200, job.status === 'done' ? { ...pub, result } : pub);
    }

    send(res, 404, { error: 'Not found' });
  } catch (err) {
    sendError(res, err);
  }
});

server.listen(PORT, '127.0.0.1', () => {
  console.log(`[bridge] listening on http://127.0.0.1:${PORT}`);
  const fs          = require('fs');
  const sessionPath = require('path').join(AUTH_PATH, 'session');
  if (fs.existsSync(sessionPath)) {
    console.log('[whatsapp] saved session found — restoring automatically…');
    createClient(); clientStarted = true;
    client.initialize().catch((err) => {
      initError = err && err.message ? err.message : String(err);
      console.error('[whatsapp] auto-restore failed:', err);
    });
  } else {
    console.log('[whatsapp] no saved session — waiting for /login');
  }
});
"""

# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------

logging.basicConfig(
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
    level=logging.INFO,
)
logger = logging.getLogger('WHbot')

# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------

BOT_TOKEN    = os.environ.get('BOT_TOKEN', '')
BRIDGE_HOST  = os.environ.get('BRIDGE_HOST', '127.0.0.1')
BRIDGE_PORT  = int(os.environ.get('BRIDGE_PORT', '3000'))
BRIDGE_TOKEN = os.environ.get('BRIDGE_TOKEN', '')

_allowed_raw = os.environ.get('ALLOWED_USER_ID', '0').strip()
try:
    ALLOWED_USER_ID: int | None = int(_allowed_raw) or None
except ValueError:
    ALLOWED_USER_ID = None

DATA_DIR = os.environ.get('DATA_DIR') or os.path.dirname(os.path.abspath(__file__))
PORT     = int(os.environ.get('PORT', '8080'))

BATCH_SIZE           = int(os.environ.get('BATCH_SIZE', '4'))
BATCH_DELAY_SECONDS  = int(os.environ.get('BATCH_DELAY_SECONDS', '30'))
ADMIN_POLL_SECONDS   = int(os.environ.get('ADMIN_POLL_SECONDS', '20'))
ADMIN_WAIT_TIMEOUT   = int(os.environ.get('ADMIN_WAIT_TIMEOUT_SECONDS', '1800'))
ADD_POLL_SECONDS     = int(os.environ.get('ADD_POLL_SECONDS', '12'))
DEFAULT_COUNTRY_CODE = os.environ.get('DEFAULT_COUNTRY_CODE', '91')

LOGIN_TIMEOUT        = 180
BRIDGE_START_TIMEOUT = 60

# ---------------------------------------------------------------------------
# Inline VCF parser
# ---------------------------------------------------------------------------

_NON_DIGITS = re.compile(r'\D')


def normalize_number(raw: str, default_cc: str = DEFAULT_COUNTRY_CODE) -> str | None:
    raw = str(raw).strip()
    if not raw:
        return None
    explicit_cc = raw.startswith('+')
    digits = _NON_DIGITS.sub('', raw)
    if not digits:
        return None
    if digits.startswith('00'):
        explicit_cc = True
        digits = digits[2:]
    if digits.startswith('0'):
        digits = digits[1:]
    if not explicit_cc and 10 <= len(digits) <= 11:
        digits = default_cc + digits
    if len(digits) < 10 or len(digits) > 15:
        return None
    return digits


def parse_vcf(file_path: str, default_cc: str = DEFAULT_COUNTRY_CODE) -> list[str]:
    try:
        import vobject
    except ImportError as exc:
        raise RuntimeError('Run: pip install -r requirements.txt') from exc

    with open(file_path, 'r', encoding='utf-8', errors='ignore') as fh:
        data = fh.read()

    numbers: list[str] = []
    try:
        for vcard in vobject.readComponents(data):
            tels = getattr(vcard, 'tel_list', [])
            if not tels and getattr(vcard, 'tel', None):
                tels = [vcard.tel]
            for tel in tels:
                num = normalize_number(tel.value, default_cc)
                if num:
                    numbers.append(num)
    except Exception as exc:
        raise ValueError(f'Malformed VCF: {exc}') from exc

    seen: set[str] = set()
    unique: list[str] = []
    for num in numbers:
        if num not in seen:
            seen.add(num)
            unique.append(num)
    return unique

# ---------------------------------------------------------------------------
# Bridge HTTP client
# ---------------------------------------------------------------------------


class BridgeError(Exception):
    pass


class Bridge:
    def __init__(self, host: str, port: int, token: str = ''):
        self.base  = f'http://{host}:{port}'
        self.token = token

    def _request(self, method: str, path: str, body=None, timeout: int = 60):
        url  = self.base + path
        data = None
        headers: dict[str, str] = {}
        if body is not None:
            data = json.dumps(body).encode('utf-8')
            headers['Content-Type'] = 'application/json'
        if self.token:
            headers['Authorization'] = f'Bearer {self.token}'
        req = urllib_request.Request(url, data=data, headers=headers, method=method)
        try:
            with urllib_request.urlopen(req, timeout=timeout) as resp:
                return json.loads(resp.read().decode('utf-8'))
        except urllib_error.HTTPError as e:
            try:
                payload = json.loads(e.read().decode('utf-8'))
                raise BridgeError(payload.get('error', f'HTTP {e.code}')) from e
            except json.JSONDecodeError:
                raise BridgeError(f'HTTP {e.code}') from e
        except urllib_error.URLError as e:
            raise BridgeError(f'Cannot reach bridge: {e.reason}') from e

    def health(self):           return self._request('GET',  '/health',               timeout=5)
    def status(self):           return self._request('GET',  '/status',               timeout=10)
    def login(self):            return self._request('POST', '/login',                timeout=10)
    def get_qr(self):           return self._request('GET',  '/qr',                   timeout=10)
    def logout(self):           return self._request('POST', '/logout',               timeout=30)
    def join_group(self, link): return self._request('POST', '/join-group', {'link': link}, timeout=60)
    def is_admin(self, gid):    return self._request('GET',  f'/admin/{quote(gid, safe="")}',   timeout=30)
    def get_members(self, gid): return self._request('GET',  f'/members/{quote(gid, safe="")}', timeout=30)
    def start_add(self, gid, contacts, batch_size, delay_seconds):
        return self._request('POST', '/add', {
            'groupId': gid, 'contacts': contacts,
            'batchSize': batch_size, 'delaySeconds': delay_seconds,
        }, timeout=15)
    def get_job(self, job_id):    return self._request('GET',  f'/jobs/{job_id}',        timeout=15)
    def cancel_job(self, job_id): return self._request('POST', f'/jobs/{job_id}/cancel', timeout=10)


bridge = Bridge(BRIDGE_HOST, BRIDGE_PORT, BRIDGE_TOKEN)

# ---------------------------------------------------------------------------
# Per-user flow state
# ---------------------------------------------------------------------------

class Flow:
    def __init__(self, user_id: int):
        self.user_id    = user_id
        self.state      = 'idle'
        self.group_id:  str | None = None
        self.group_name = ''
        self.contacts:  list[str] = []
        self.job_id:    str | None = None
        self.started_at = 0.0


flows: dict[int, Flow] = {}
APP: Application | None = None


def get_flow(user_id: int) -> Flow:
    if user_id not in flows:
        flows[user_id] = Flow(user_id)
    return flows[user_id]


def allowed(user_id: int) -> bool:
    return ALLOWED_USER_ID is None or user_id == ALLOWED_USER_ID

# ---------------------------------------------------------------------------
# Session ownership
# ---------------------------------------------------------------------------

OWNER_FILE = os.path.join(DATA_DIR, 'session_owner.json')
SESSION_OWNER:    int | None = None
LOGIN_PENDING_BY: int | None = None


def load_session_owner() -> int | None:
    global SESSION_OWNER
    try:
        with open(OWNER_FILE, 'r', encoding='utf-8') as fh:
            data = json.load(fh)
        raw = data.get('user_id')
        SESSION_OWNER = int(raw) if raw else None
    except (OSError, ValueError, TypeError):
        SESSION_OWNER = None
    if SESSION_OWNER:
        logger.info('Loaded session owner: %s', SESSION_OWNER)
    return SESSION_OWNER


def set_session_owner(user_id: int | None) -> None:
    global SESSION_OWNER
    SESSION_OWNER = int(user_id) if user_id else None
    try:
        with open(OWNER_FILE, 'w', encoding='utf-8') as fh:
            json.dump({'user_id': SESSION_OWNER}, fh)
    except OSError:
        logger.warning('Could not persist session owner: %s', OWNER_FILE)


def current_owner() -> int | None:
    global SESSION_OWNER
    if SESSION_OWNER is None:
        return None
    try:
        st = bridge.status()
        if not st.get('loggedIn'):
            set_session_owner(None)
            return None
    except BridgeError:
        return SESSION_OWNER
    return SESSION_OWNER


def owner_blocked(user_id: int) -> str | None:
    owner = current_owner()
    if owner is None:
        return (
            '❌ No WhatsApp session is linked.\n'
            'Use /login to scan a QR — the user who scans it becomes the only one who can use the bot.'
        )
    if user_id != owner:
        return (
            "❌ This bot is linked to another user's WhatsApp number. "
            'Ask them to /logout when done.'
        )
    return None


def qr_to_bytes(qr_string: str) -> io.BytesIO:
    img = qrcode.make(qr_string)
    buf = io.BytesIO()
    img.save(buf, format='PNG')
    buf.seek(0)
    return buf

# ---------------------------------------------------------------------------
# Bridge process — write embedded JS and spawn it
# ---------------------------------------------------------------------------

_bridge_js_path: str | None = None


def _write_bridge_script() -> str:
    global _bridge_js_path
    if _bridge_js_path and os.path.exists(_bridge_js_path):
        return _bridge_js_path
    os.makedirs(DATA_DIR, exist_ok=True)
    dest = os.path.join(DATA_DIR, 'whatsapp_bridge.js')
    with open(dest, 'w', encoding='utf-8') as fh:
        fh.write(BRIDGE_JS)
    _bridge_js_path = dest
    logger.info('Bridge script written to: %s', dest)
    return dest


async def ensure_bridge_running() -> subprocess.Popen | None:
    try:
        bridge.health()
        logger.info('Reusing already-running bridge.')
        return None
    except BridgeError:
        pass

    script   = _write_bridge_script()
    bot_dir  = os.path.dirname(os.path.abspath(__file__))
    # node_modules must be next to WHbot.py (after npm install)
    cwd = bot_dir
    if not os.path.isdir(os.path.join(bot_dir, 'node_modules')):
        logger.warning(
            'node_modules not found in %s. Run: npm install', bot_dir
        )

    env = dict(os.environ)
    env.setdefault('WWEBJS_AUTH_PATH', os.path.join(DATA_DIR, '.wwebjs_auth'))

    proc = subprocess.Popen(['node', script], cwd=cwd, env=env)

    for _ in range(BRIDGE_START_TIMEOUT):
        try:
            bridge.health()
            logger.info('Bridge started (pid %s).', proc.pid)
            return proc
        except BridgeError:
            await asyncio.sleep(1)

    try:
        proc.terminate()
    except Exception:
        pass
    raise RuntimeError(
        'Bridge failed to start within 60 s.\n'
        'Make sure Node.js >= 18 is installed and you ran: npm install'
    )

# ---------------------------------------------------------------------------
# Telegram handlers
# ---------------------------------------------------------------------------

async def cmd_start(update: Update, context: ContextTypes.DEFAULT_TYPE):
    if not allowed(update.effective_user.id):
        return await update.message.reply_text('Access denied.')
    await update.message.reply_text(
        '🤖 *WhatsApp Group Manager*\n\n'
        'Workflow:\n'
        '1. `/login` — link your WhatsApp (scan the QR).\n'
        '2. `/join <group_link>` — join a group with that number.\n'
        '3. Bot waits until the number is made *admin* in the group.\n'
        f'4. Send a `.vcf` file — contacts added in batches of {BATCH_SIZE} '
        f'with {BATCH_DELAY_SECONDS}s delay.\n'
        '5. Receive a final report.\n\n'
        'Commands: `/login` `/logout` `/join` `/status` `/cancel`',
        parse_mode='Markdown',
    )


async def cmd_login(update: Update, context: ContextTypes.DEFAULT_TYPE):
    global LOGIN_PENDING_BY
    user_id = update.effective_user.id
    if not allowed(user_id):
        return await update.message.reply_text('Access denied.')

    flow = get_flow(user_id)
    if flow.state in ('waiting_admin', 'adding'):
        return await update.message.reply_text('You have an active flow. Use /cancel first.')

    if LOGIN_PENDING_BY is not None and LOGIN_PENDING_BY != user_id:
        return await update.message.reply_text(
            '⏳ Another user is currently logging in. Wait for them to finish.'
        )

    owner = current_owner()
    if owner is not None:
        if owner != user_id:
            return await update.message.reply_text(
                "❌ This bot is linked to another user's WhatsApp. Ask them to /logout first."
            )
        try:
            res = bridge.login()
        except BridgeError as e:
            return await update.message.reply_text(f'❌ Failed to start login: {e}')
        return await update.message.reply_text(
            f'✅ Already logged in as {res.get("info") or "your number"}.'
        )

    try:
        status = bridge.status()
        if status.get('loggedIn'):
            await update.message.reply_text(
                '♻️ A WhatsApp session exists but has no owner. Logging it out and linking *your* number…',
                parse_mode='Markdown',
            )
            bridge.logout()
    except BridgeError as e:
        return await update.message.reply_text(f'❌ {e}')

    LOGIN_PENDING_BY = user_id
    try:
        bridge.login()
    except BridgeError as e:
        LOGIN_PENDING_BY = None
        return await update.message.reply_text(f'❌ Failed to start login: {e}')

    await update.message.reply_text(
        '📲 Starting WhatsApp login…\n'
        'Open WhatsApp → *Settings → Linked Devices → Link a Device* and scan the QR.\n'
        'Session is saved — you only do this once.',
        parse_mode='Markdown',
    )
    APP.create_task(login_loop(update.effective_chat.id, user_id))


async def login_loop(chat_id: int, user_id: int):
    global LOGIN_PENDING_BY
    deadline = time.time() + LOGIN_TIMEOUT
    sent_qr  = False
    try:
        while time.time() < deadline:
            res   = bridge.get_qr()
            state = res.get('state')
            if state == 'error':
                await APP.bot.send_message(
                    chat_id,
                    f'❌ WhatsApp client failed:\n`{res.get("error", "unknown")}`\n\n'
                    'Make sure Chrome/Chromium is installed and `npm install` was run.',
                    parse_mode='Markdown',
                )
                return
            if state == 'ready':
                status = bridge.status()
                set_session_owner(user_id)
                await APP.bot.send_message(
                    chat_id,
                    f'✅ Logged in as {status.get("info", "your number")}. '
                    'Session saved — only you can use this bot now.',
                )
                return
            if res.get('qr') and not sent_qr:
                sent_qr = True
                await APP.bot.send_photo(
                    chat_id,
                    InputFile(qr_to_bytes(res['qr']), filename='qr.png'),
                    caption='Scan with WhatsApp → Linked Devices. If it expires, send /login again.',
                )
            await asyncio.sleep(3)
        await APP.bot.send_message(chat_id, '⏰ Login timed out. Send /login again for a fresh QR.')
    except BridgeError as e:
        await APP.bot.send_message(chat_id, f'❌ Login error: {e}')
    except Exception:
        logger.exception('login_loop failed')
        await APP.bot.send_message(chat_id, '❌ Unexpected error during login.')
    finally:
        if LOGIN_PENDING_BY == user_id:
            LOGIN_PENDING_BY = None


async def cmd_join(update: Update, context: ContextTypes.DEFAULT_TYPE):
    user_id = update.effective_user.id
    if not allowed(user_id):
        return await update.message.reply_text('Access denied.')
    blocked = owner_blocked(user_id)
    if blocked:
        return await update.message.reply_text(blocked)

    try:
        status = bridge.status()
        if not status.get('loggedIn'):
            return await update.message.reply_text('❌ Not logged in. Use /login first.')
    except BridgeError as e:
        return await update.message.reply_text(f'❌ {e}')

    flow = get_flow(user_id)
    if flow.state in ('waiting_admin', 'adding'):
        return await update.message.reply_text('You have an active flow. Use /cancel first.')

    if context.args:
        return await join_with_link(update, user_id, context.args[0])

    flow.state = 'waiting_group_link'
    await update.message.reply_text('🔗 Send the WhatsApp group invite link (https://chat.whatsapp.com/…).')


async def join_with_link(update: Update, user_id: int, link: str):
    flow = get_flow(user_id)
    try:
        res = bridge.join_group(link)
    except BridgeError as e:
        return await update.message.reply_text(f'❌ Failed to join: {e}\n\nTry again with /join <link>.')

    flow.group_id   = res['groupId']
    flow.group_name = res.get('name', '')
    flow.state      = 'waiting_admin'
    flow.started_at = time.time()
    await update.message.reply_text(
        f'✅ Joined *"{flow.group_name}"*.\n\n'
        '⏳ Waiting for *admin rights* for this number…\n'
        'Open WhatsApp → Group Info → Admins and promote this number. '
        'I will continue automatically once confirmed.',
        parse_mode='Markdown',
    )
    APP.create_task(wait_admin_loop(update.effective_chat.id, user_id))


async def wait_admin_loop(chat_id: int, user_id: int):
    flow = get_flow(user_id)
    announced = False
    elapsed   = 0
    try:
        while flow.state == 'waiting_admin' and elapsed < ADMIN_WAIT_TIMEOUT:
            try:
                res = bridge.is_admin(flow.group_id)
                if res.get('isAdmin'):
                    flow.state = 'waiting_vcf'
                    await APP.bot.send_message(
                        chat_id,
                        '✅ *Admin rights confirmed!*\n'
                        f'Now send the `.vcf` file with contacts to add to "{flow.group_name}".',
                        parse_mode='Markdown',
                    )
                    return
            except BridgeError:
                pass
            await asyncio.sleep(ADMIN_POLL_SECONDS)
            elapsed += ADMIN_POLL_SECONDS
            if not announced and elapsed >= 60:
                announced = True
                await APP.bot.send_message(
                    chat_id, f'⏳ Still waiting for admin rights… (checking every {ADMIN_POLL_SECONDS}s)'
                )
        if flow.state == 'waiting_admin':
            flow.state = 'idle'
            await APP.bot.send_message(
                chat_id,
                '❌ Timed out waiting for admin. Promote the number, then /join <link> again.',
            )
    except Exception as e:
        logger.exception('wait_admin_loop failed')
        flow.state = 'idle'
        await APP.bot.send_message(chat_id, f'❌ Error waiting for admin: {e}')


async def on_text(update: Update, context: ContextTypes.DEFAULT_TYPE):
    user_id = update.effective_user.id
    if not allowed(user_id):
        return
    blocked = owner_blocked(user_id)
    if blocked:
        return await update.message.reply_text(blocked)

    flow = get_flow(user_id)
    text = (update.message.text or '').strip()
    looks_like_link = 'chat.whatsapp.com' in text or 'whatsapp.com' in text

    if flow.state == 'waiting_group_link' or (flow.state == 'idle' and looks_like_link):
        if flow.state == 'idle':
            try:
                status = bridge.status()
                if not status.get('loggedIn'):
                    return await update.message.reply_text('❌ Not logged in. Use /login first.')
            except BridgeError as e:
                return await update.message.reply_text(f'❌ {e}')
        await join_with_link(update, user_id, text)


async def on_document(update: Update, context: ContextTypes.DEFAULT_TYPE):
    user_id = update.effective_user.id
    if not allowed(user_id):
        return
    blocked = owner_blocked(user_id)
    if blocked:
        return await update.message.reply_text(blocked)

    flow = get_flow(user_id)
    doc  = update.message.document

    if not (doc.file_name or '').lower().endswith('.vcf'):
        return await update.message.reply_text('Please send a `.vcf` file.')

    if flow.state != 'waiting_vcf':
        return await update.message.reply_text(
            'You are not in the "waiting for VCF" step.\n'
            'Use /join <group_link> first and wait for admin confirmation.'
        )

    tmp_path = os.path.join(tempfile.gettempdir(), f'contacts_{user_id}_{int(time.time())}.vcf')
    try:
        file = await doc.get_file()
        await file.download_to_drive(tmp_path)
        contacts = parse_vcf(tmp_path, DEFAULT_COUNTRY_CODE)
    except Exception as e:
        logger.exception('VCF parse failed')
        return await update.message.reply_text(f'❌ Could not parse VCF: {e}')
    finally:
        try:
            os.remove(tmp_path)
        except OSError:
            pass

    if not contacts:
        return await update.message.reply_text(
            '⚠️ No usable numbers found in the VCF.\n'
            'Check numbers include a country code, or set DEFAULT_COUNTRY_CODE.'
        )

    flow.contacts = [f'{num}@c.us' for num in contacts]
    keyboard = InlineKeyboardMarkup([[
        InlineKeyboardButton('✅ Start adding', callback_data='start_add'),
        InlineKeyboardButton('❌ Cancel',       callback_data='cancel_add'),
    ]])
    await update.message.reply_text(
        f'📇 Found *{len(contacts)} unique numbers* in the VCF.\n'
        f'Adding to *"{flow.group_name}"* in batches of {BATCH_SIZE} '
        f'with {BATCH_DELAY_SECONDS}s delay.\n\nStart?',
        reply_markup=keyboard,
        parse_mode='Markdown',
    )


async def on_callback(update: Update, context: ContextTypes.DEFAULT_TYPE):
    query = update.callback_query
    await query.answer()
    user_id = query.from_user.id
    if not allowed(user_id):
        return
    blocked = owner_blocked(user_id)
    if blocked:
        return await query.edit_message_text(blocked)

    flow = get_flow(user_id)
    if query.data == 'cancel_add':
        flow.contacts = []
        flow.state    = 'idle'
        return await query.edit_message_text('Cancelled.')

    if query.data == 'start_add':
        if not flow.contacts or not flow.group_id:
            flow.state = 'idle'
            return await query.edit_message_text('❌ Missing data. Start over with /join.')
        await query.edit_message_text('🚀 Adding contacts… I will send progress updates.')
        APP.create_task(run_add_flow(query.message.chat_id, user_id))


async def run_add_flow(chat_id: int, user_id: int):
    flow       = get_flow(user_id)
    flow.state = 'adding'
    try:
        res         = bridge.start_add(flow.group_id, flow.contacts, BATCH_SIZE, BATCH_DELAY_SECONDS)
        flow.job_id = res['jobId']
        last_rep    = 0

        while True:
            job    = bridge.get_job(flow.job_id)
            status = job.get('status')
            if status in ('done', 'error', 'cancelled'):
                break
            done = job.get('doneBatches', 0)
            if done > last_rep:
                last_rep = done
                await APP.bot.send_message(
                    chat_id,
                    f'📦 Batch {done}/{job.get("totalBatches","?")} — '
                    f'added {job.get("added",0)}, failed {job.get("failed",0)}.',
                )
            await asyncio.sleep(ADD_POLL_SECONDS)

        if status == 'done':
            result  = job.get('result', {})
            added   = result.get('added',  [])
            failed  = result.get('failed', [])
            members = bridge.get_members(flow.group_id)
            lines   = [
                '✅ *Adding complete!*', '',
                f'• Added:           *{len(added)}*',
                f'• Already in group: *{result.get("alreadyCount", 0)}*',
                f'• Failed:          *{len(failed)}*',
                f'• Final group size: *{members.get("count","?")}*',
            ]
            if failed:
                sample = ', '.join(f.get('id','?').split('@')[0] for f in failed[:10])
                lines.append(f'\n⚠️ Failed ({len(failed)}): {sample}')
                if len(failed) > 10:
                    lines.append('…')
            await APP.bot.send_message(chat_id, '\n'.join(lines), parse_mode='Markdown')
        elif status == 'cancelled':
            await APP.bot.send_message(chat_id, '❌ Adding was cancelled.')
        else:
            await APP.bot.send_message(chat_id, f'❌ Adding failed: {job.get("error","unknown")}')
    except BridgeError as e:
        await APP.bot.send_message(chat_id, f'❌ Error: {e}')
    except Exception as e:
        logger.exception('run_add_flow failed')
        await APP.bot.send_message(chat_id, f'❌ Unexpected error: {e}')
    finally:
        flow.state    = 'idle'
        flow.contacts = []
        flow.job_id   = None


async def cmd_status(update: Update, context: ContextTypes.DEFAULT_TYPE):
    user_id = update.effective_user.id
    if not allowed(user_id):
        return await update.message.reply_text('Access denied.')
    blocked = owner_blocked(user_id)
    if blocked:
        return await update.message.reply_text(blocked)
    try:
        st = bridge.status()
    except BridgeError as e:
        return await update.message.reply_text(f'❌ Bridge error: {e}')

    flow  = get_flow(user_id)
    wa    = f'✅ logged in as {st.get("info")}' if st.get('loggedIn') else '❌ not logged in'
    lines = [f'WhatsApp: {wa}', f'Flow: `{flow.state}`']
    if flow.group_name:
        lines.append(f'Group: {flow.group_name}')
    if flow.job_id:
        lines.append(f'Job: {flow.job_id}')
    await update.message.reply_text('\n'.join(lines), parse_mode='Markdown')


async def cmd_logout(update: Update, context: ContextTypes.DEFAULT_TYPE):
    user_id = update.effective_user.id
    if not allowed(user_id):
        return await update.message.reply_text('Access denied.')
    blocked = owner_blocked(user_id)
    if blocked:
        return await update.message.reply_text(blocked)
    try:
        bridge.logout()
        set_session_owner(None)
        await update.message.reply_text('🚪 Logged out. Anyone can now /login as the new owner.')
    except BridgeError as e:
        await update.message.reply_text(f'❌ {e}')


async def cmd_cancel(update: Update, context: ContextTypes.DEFAULT_TYPE):
    user_id = update.effective_user.id
    if not allowed(user_id):
        return await update.message.reply_text('Access denied.')
    blocked = owner_blocked(user_id)
    if blocked:
        return await update.message.reply_text(blocked)
    flow = get_flow(user_id)
    if flow.state == 'adding' and flow.job_id:
        try:
            bridge.cancel_job(flow.job_id)
        except BridgeError:
            pass
    flow.state    = 'idle'
    flow.contacts = []
    flow.job_id   = None
    await update.message.reply_text('Current flow cancelled.')

# ---------------------------------------------------------------------------
# Health-check server
# ---------------------------------------------------------------------------

async def _health_handler(reader, writer):
    try:
        await reader.read(4096)
    except Exception:
        pass
    try:
        writer.write(b'HTTP/1.1 200 OK\r\nContent-Length: 2\r\nConnection: close\r\n\r\nOK')
        await writer.drain()
    except Exception:
        pass
    finally:
        writer.close()
        try:
            await writer.wait_closed()
        except Exception:
            pass


async def start_health_server() -> asyncio.Server | None:
    try:
        server = await asyncio.start_server(_health_handler, '0.0.0.0', PORT)
        logger.info('Health server on port %s', PORT)
        return server
    except OSError as e:
        logger.warning('Health server failed on port %s: %s', PORT, e)
        return None

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

async def main():
    global APP
    if not BOT_TOKEN:
        raise SystemExit('❌ Set BOT_TOKEN in your .env file before starting!')

    os.makedirs(DATA_DIR, exist_ok=True)
    logger.info('Data dir: %s', DATA_DIR)

    load_session_owner()
    bridge_proc = await ensure_bridge_running()

    APP = Application.builder().token(BOT_TOKEN).build()
    APP.add_handler(CommandHandler('start',  cmd_start))
    APP.add_handler(CommandHandler('login',  cmd_login))
    APP.add_handler(CommandHandler('logout', cmd_logout))
    APP.add_handler(CommandHandler('join',   cmd_join))
    APP.add_handler(CommandHandler('status', cmd_status))
    APP.add_handler(CommandHandler('cancel', cmd_cancel))
    APP.add_handler(MessageHandler(filters.TEXT & ~filters.COMMAND, on_text))
    APP.add_handler(MessageHandler(filters.Document.ALL, on_document))
    APP.add_handler(CallbackQueryHandler(on_callback))

    health_server = await start_health_server()
    try:
        await APP.initialize()
        await APP.updater.start_polling()
        await APP.start()
        logger.info('✅ Bot is running! Press Ctrl+C to stop.')

        loop       = asyncio.get_running_loop()
        stop_event = asyncio.Event()

        def _shutdown(sig_name: str):
            logger.info('Received %s — shutting down…', sig_name)
            stop_event.set()

        for sig, name in ((signal.SIGINT, 'SIGINT'), (signal.SIGTERM, 'SIGTERM')):
            try:
                loop.add_signal_handler(sig, lambda n=name: _shutdown(n))
            except (NotImplementedError, RuntimeError):
                pass

        await stop_event.wait()
    finally:
        if health_server:
            health_server.close()
            try:
                await health_server.wait_closed()
            except Exception:
                pass
        if bridge_proc:
            try:
                bridge_proc.terminate()
            except Exception:
                pass
        if APP.updater and APP.updater.running:
            await APP.updater.stop()
        if APP.running:
            await APP.stop()
        await APP.shutdown()


if __name__ == '__main__':
    try:
        asyncio.run(main())
    except KeyboardInterrupt:
        pass
